### ISSUE TITLE
propose the ability to receive Unity shadow in GraphicsTools StandardShader 

### ISSUE THREAD

**Issue by HoloMoto** [microsoft/MixedReality-GraphicsTools-Unity#125] opened 2022-11-27 06:43 UTC
## Describe the problem

I propose the ability to receive Unity shadow in GraphicsTools StandardShader .

![スクリーンショット 2022-11-27 152655](https://user-images.githubusercontent.com/36409613/204122535-3dec048d-0391-49cb-b73f-58f44b08f6eb.jpg)

MRGTShader is lightweight, has many features, and can run on various platforms as well as HoloLens.

Although HoloLens did not require much functionality to receive shadows, there were situations where the specifications of the device and the nature of the application, such as VR and MagicLeap2, required the ability to receive shadows.

For example, I am currently using MRGT not only for HoloLens but also for VR games.

I am using it as a replacement for the traditional StandardShader, but in this case I sometimes wanted to receive shadows on objects such as stages.

　I thought it would be nice if I could optionally set up the receipt of shadows in the GraphicsToolsStandardShader.

　The image in the screenshot is a test of the functionality in URP.

　I need to add it to work in BuildIn as well.

　Also as you can see in the screenshot I planed CastShadow in the future as well.
　However, in this issue I will only work on receive shadows and create a separate issue.

## Describe the solution you'd like

I will submit the feature shortly.

**Comment by Cameron-Micka** [comment] 2022-11-28 20:14
Great idea @HoloMoto, we have a similar issue here: https://github.com/microsoft/MixedReality-GraphicsTools-Unity/issues/55

**Comment by Cameron-Micka** [comment] 2022-12-08 21:38
Closing as duplicate of #55

**Closed by Cameron-Micka** 2022-12-08 21:38 UTC
Labels: duplicate, enhancement
